# Keep the complete fork version in desktop/session metadata. The session's
# numeric conversion reads the optional Windows revision from the suffix.
if(NOT RSTUDIO_FORK_VERSION MATCHES "^([0-9]+)\\.([0-9]+)\\.([0-9]+)(\\.([0-9]+))?(-[0-9A-Za-z]+(\\.[0-9A-Za-z]+)*)?$")
   message(FATAL_ERROR "RSTUDIO_FORK_VERSION must have three or four numeric components with an optional prerelease suffix")
endif()
set(CPACK_PACKAGE_VERSION_MAJOR "${CMAKE_MATCH_1}")
set(CPACK_PACKAGE_VERSION_MINOR "${CMAKE_MATCH_2}")
set(CPACK_PACKAGE_VERSION_PATCH "${CMAKE_MATCH_3}")
set(CPACK_PACKAGE_VERSION_REVISION "${CMAKE_MATCH_5}")
set(CPACK_PACKAGE_VERSION_SUFFIX "${CMAKE_MATCH_4}${CMAKE_MATCH_6}")
set(CPACK_PACKAGE_VERSION "${RSTUDIO_FORK_VERSION}")
if(CPACK_PACKAGE_VERSION_REVISION STREQUAL "")
   set(CPACK_PACKAGE_VERSION_REVISION "0")
endif()
foreach(part MAJOR MINOR PATCH REVISION)
   if(CPACK_PACKAGE_VERSION_${part} GREATER 65535)
      message(FATAL_ERROR "Numeric version components must fit Windows version fields")
   endif()
endforeach()
